modLoader = "javafml"
loaderVersion = "[35,)"
license = "All rights reserved"

[[mods]]
modId = "banana"
version = "${file.jarVersion}"
displayName = "Banana"
credits = "Thanks for this example mod goes to Java"
authors = "mkaito"
description = '''
This is a very crappy mod made by a crappy dev. It might eat your dog.
'''

[[dependencies.banana]]
modId = "forge"
mandatory = true
versionRange = "[35,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.banana]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.4,1.17)"
ordering = "NONE"
side = "BOTH"
